add rabbit
YoungSeokHong/Let-s-Study-Git pull request #4
Opened 2022-03-15 10:13 UTC by MiniVee

Good

2022-03-16 02:54 UTC, YoungSeokHong requested changes

2022-03-16 02:54 UTC, YoungSeokHong commented on rabbit.txt
> +age : 26
이름 bani로 수정해주시고 나이는 24살로 수정해주세요!
```
name : bani
age : 24
```
로 해주시면 됩니다!

2022-03-16 06:28 UTC, MiniVee commented on rabbit.txt
> +age : 26
I modify rabbit.txt
Can you check rabbit.txt?
Tank you :)

2022-03-17 08:02 UTC, YoungSeokHong approved these changes
LGTM : )

2022-03-17 08:02 UTC, YoungSeokHong commented on rabbit.txt
> +age : 24
고생하셨습니다!

2022-03-17 08:02 UTC, merged