Add Quokka
YoungSeokHong/Let-s-Study-Git pull request #7
Opened 2022-03-17 18:18 UTC by seojeongyoon

Hello! I have completed my full request.
Please check it.

2022-03-18 14:02 UTC, YoungSeokHong requested changes

2022-03-18 14:02 UTC, YoungSeokHong commented on quokka.txt
> +age : 4
죄송합니다 늦게 확인했네요 ㅠㅠ
이름을 Kakao 나이를 12살로 바꿔주세요.
```
name : Kakao
age : 12
```
로 바꿔주시면 될 것 같습니다!

2022-03-23 06:36 UTC, seojeongyoon commented
수정사항 반영했습니다!

2022-03-24 16:28 UTC, YoungSeokHong approved these changes
LGTM : )

2022-03-24 16:28 UTC, YoungSeokHong commented on quokka.txt
> +age : 12
고생하셨습니다!

2022-03-24 16:28 UTC, merged